
stop_words = ['zbog','protiv','video','foto','nije', 'nego','koji',\
             'novi', 'više','ljudi','pred','zašto','zato','kako','nema',\
             'treba','svoje','samo', 'danas','sutra', 'dalje', 'novog',\
             'vesti', 'ovako', 'prva', 'neće', 'niko','dana','biti','mogao','godina',\
             'srbije', 'srbiji','srbiju','predsednik', 'predsednika','trebalo','počne','premijer',\
             'opet', 'svet','sport', 'srpska', 'bivši', 'grad', 'gradu','premijeru','premijera',\
             'spoljnih','ministar', 'ministra', 'republika','republike', 'ministarstvo', 'ministarstva',\
             'izjavio', 'može', 'saopštenju', 'saopštila', 'prenela', 'agencija', 'direktor', 'kancelarije',\
             'jutros', 'rano', 'navodno','time', 'navodni', 'bavi', 'broj','član', 'kojima', 'poslova', 'srpski',\
             'ministrom', 'srpskih','posle','rekao','navodne','kancelarka', 'kancelarke','kancelarki','koje','potom'\
             'saznaje','prenosi', 'javlja', 'saopštio', 'saopštenje','koja','osoba',"(",")","%"
             ]



lokacija = [
 'Aleksandrovac',
 'Aleksinac',
 'Alibunar',
 'Apatin',
 'Aranđelovac',
 'Arilje',
 'Babušnica',
 'Bajina Bašta',
 'Barajevo',
 'Batočina',
 'Bač',
 'Bačka Palanka',
 'Bačka Topola',
 'Bački Petrovac',
 'Bela Crkva',
 'Bela Palanka',
 'Beočin',
 'Bečej',
 'Blace',
 'Bogatić',
 'Bojnik',
 'Boljevac',
 'Bosilegrad',
 'Brus',
 'Bujanovac',
 'Crna Trava',
 'Despotovac',
 'Dimitrovgrad',
 'Doljevac',
 'Gadžin Han',
 'Golubac',
 'Gornji Milanovac',
 'Niš',
 'Grocka',
 'Inđija',
 'Irig',
 'Ivanjica',
 'Jagodina',
 'Kanjiža',
 'Kikinda',
 'Kladovo',
 'Knić',
 'Knjaževac',
 'Koceljeva',
 'Kosjerić',
 'Kovačica',
 'Kovin',
 'Kragujevac',
 'Kraljevo',
 'Krupanj',
 'Kruševac',
 'Kula',
 'Kuršumlija',
 'Kučevo',
 'Lajkovac',
 'Lapovo',
 'Lazarevac',
 'Lebane',
 'Leskovac',
 'Loznica',
 'Lučani',
 'Majdanpek',
 'Mali Iđoš',
 'Mali Zvornik',
 'Malo Crniće',
 'Medveđa',
 'Merošina',
 'Mionica',
 'Mladenovac',
 'Negotin',
 'Nova Crnja',
 'Nova Varoš',
 'Novi Beograd',
 'Novi Bečej',
 'Novi Kneževac',
 'Novi Pazar',
 'Novi Sad',
 'Obrenovac',
 'Opovo',
 'Osečina',
 'Odžaci',
 'Palilula',
 'Pančevo',
 'Paraćin',
 'Petrovac',
 'Pećinci',
 'Pirot',
 'Plandište',
 'Požarevac',
 'Požega',
 'Preševo',
 'Priboj',
 'Prijepolje',
 'Prokuplje',
 'Ljig',
 'Ljubovija',
 'Rača',
 'Raška',
 'Ražanj',
 'Rekovac',
 'Ruma',
 'Savski venac',
 'Senta',
 'Sečanj',
 'Sjenica',
 'Smederevo',
 'Smederevska Palanka',
 'Sokobanja',
 'Sombor',
 'Sopot',
 'Srbobran',
 'Sremska Mitrovica',
 'Sremski Karlovci',
 'Stara Pazova',
 'Subotica',
 'Surdulica',
 'Surčin',
 'Svilajnac',
 'Svrljig',
 'Temerin',
 'Titel',
 'Topola',
 'Trgovište',
 'Trstenik',
 'Tutin',
 'Užice',
 'Valjevo',
 'Varvarin',
 'Velika Plana',
 'Veliko Gradište',
 'Vladimirci',
 'Vladičin Han',
 'Vlasotince',
 'Vranje',
 'Vrbas',
 'Vrnjačka Banja',
 'Vršac',
 'Zaječar',
 'Zemun',
 'Zrenjanin',
 'Zvezdara',
 'Ćićevac',
 'Ćuprija',
 'Čajetina',
 'Čačak',
 'Čoka',
 'Šabac',
 'Šid',
 'Žabalj',
 'Žabari',
 'Žagubica',
 'Žitište',
 'Žitorađa',
 'Kostolac',
 'Beograd',
 'Priština',
 'Kosovska Mitrovica',
 'Aleksandrovcu',
 'Aleksincu',
 'Alibunaru',
 'Apatinu',
 'Aranđelovac',
 'Arilju',
 'Babušnici',
 'Bajinoj Bašti',
 'Batočini',
 'Baču',
 'Bačkoj Palanci',
 'Bačkoj Topoli',
 'Bačkom Petrovcu',
 'Beloj Crkvi',
 'Beloj Palankci',
 'Beočinu',
 'Bečeju',
 'Blacu',
 'Bogatiću',
 'Bojniku',
 'Boljevcu',
 'Bosilegradu',
 'Brusu',
 'Bujanovcu',
 'Crnoj Travi',
 'Despotovcu',
 'Dimitrovgradu',
 'Doljevcu',
 'Gadžinom Hanu',
 'Golupcu',
 'Gornjem Milanovcu',
 'Nišu',
 'Grockoj',
 'Inđiji',
 'Irigu',
 'Ivanjici',
 'Jagodini',
 'Kanjiži',
 'Kikindi',
 'Kladovu',
 'Kniću',
 'Knjaževcu',
 'Koceljevi',
 'Kosjeriću',
 'Kovačici',
 'Kovinu',
 'Kragujevcu',
 'Kraljevu',
 'Krupnju',
 'Kruševcu',
 'Kuli',
 'Kuršumliji',
 'Kučevu',
 'Lajkovcu',
 'Lapovu',
 'Lazarevcu',
 'Lebanu',
 'Leskovcu',
 'Loznici',
 'Lučanima',
 'Majdanpeku',
 'Malom Iđošu',
 'Malom Zvorniku',
 'Malom Crniću',
 'Medveđi',
 'Merošini',
 'Mionici',
 'Mladenovcu',
 'Negotinu',
 'Novoj Crnji',
 'Novoj Varoši',
 'Novom Beogradu',
 'Novom Bečeju',
 'Novom Kneževcu',
 'Novom Pazaru',
 'Novom Sadu',
 'Obrenovcu',
 'Opovu',
 'Osečini',
 'Odžacima',
 'Pančevu',
 'Paraćinu',
 'Petrovcu',
 'Pećincima',
 'Pirotu',
 'Plandištu',
 'Požarevcu',
 'Požegi',
 'Preševu',
 'Priboju',
 'Prijepolju',
 'Prokuplju',
 'Ljigu',
 'Ljuboviju',
 'Rači',
 'Raški',
 'Ražnju',
 'Rekovcu',
 'Rumi',
 'Senti',
 'Sečnju',
 'Sjenici',
 'Smederevu',
 'Smederevskoj Palanci',
 'Sokobanji',
 'Somboru',
 'Sopotu',
 'Srbobranu',
 'Sremskoj Mitrovici',
 'Sremskim Karlovcima',
 'Staroj Pazovi',
 'Subotici',
 'Surdulici',
 'Surčinu',
 'Svilajncu',
 'Svrljigu',
 'Temerinu',
 'Titelu',
 'Topoli',
 'Trgovištu',
 'Trsteniku',
 'Tutinu',
 'Užicu',
 'Valjevu',
 'Varvarinu',
 'Velikoj Plani',
 'Velikom Gradištu',
 'Vladimircima',
 'Vladičinom Hanu',
 'Vlasotincu',
 'Vranju',
 'Vrbasu',
 'Vrnjačkoj Banji',
 'Vršcu',
 'Zaječaru',
 'Zemunu',
 'Zrenjaninu',
 'Ćićevcu',
 'Ćupriji',
 'Čajetini',
 'Čačku',
 'Čoki',
 'Šapcu',
 'Šidu',
 'Žablju',
 'Žabarima',
 'Žagubici',
 'Žitištu',
 'Žitorađi',
 'Kostolcu',
 'Beogradu',
 'Prištini',
 'Kosovskoj Mitrovici',
 'Aleksandrovca',
 'Aleksinca',
 'Alibunara',
 'Apatina',
 'Aranđelovca',
 'Arilja',
 'Babušnice',
 'Bajine Bašte',
 'Barajeva',
 'Batočine',
 'Bača',
 'Bačke Palanke',
 'Bačke Topole',
 'Bačkog Petrovca',
 'Bele Crkve',
 'Bele Palanke',
 'Beočina',
 'Bečeja',
 'Blaca',
 'Bogatića',
 'Bojnika',
 'Boljevca',
 'Bosilegrada',
 'Brusa',
 'Bujanovca',
 'Crne Trave',
 'Despotovca',
 'Dimitrovgrada',
 'Doljevca',
 'Gadžinog Hana',
 'Golupca',
 'Gornjeg Milanovca',
 'Niša',
 'Grocke',
 'Inđije',
 'Iriga',
 'Ivanjice',
 'Jagodine',
 'Kanjiže',
 'Kikinde',
 'Kladova',
 'Knića',
 'Knjaževca',
 'Koceljeve',
 'Kosjerića',
 'Kovačice',
 'Kovina',
 'Kragujevca',
 'Kraljeva',
 'Krupnja',
 'Kruševca',
 'Kule',
 'Kuršumlije',
 'Kučeva',
 'Lajkovca',
 'Lapova',
 'Lazarevca',
 'Lebana',
 'Leskovca',
 'Loznice',
 'Lučana',
 'Majdanpeka',
 'Malog Iđoša',
 'Malog Zvornika',
 'Malog Crnića',
 'Medveđe',
 'Merošine',
 'Mionice',
 'Mladenovca',
 'Negotina',
 'Nove Crnje',
 'Nove Varoši',
 'Novog Beograda',
 'Novog Bečeja',
 'Novog Kneževca',
 'Novog Pazara',
 'Novog Sada',
 'Obrenovaca',
 'Opova',
 'Osečine',
 'Odžaka',
 'Palilule',
 'Pančeva',
 'Paraćina',
 'Petrovca',
 'Pećinaca',
 'Pirota',
 'Plandišta',
 'Požarevca',
 'Požege',
 'Preševa',
 'Priboja',
 'Prijepolja',
 'Prokuplja',
 'Ljiga',
 'Ljubovije',
 'Rače',
 'Raške',
 'Ražnja',
 'Rekovca',
 'Rume',
 'Sente',
 'Sečnja',
 'Sjenice',
 'Smedereva',
 'Smederevske Palanke',
 'Sokobanje',
 'Sombora',
 'Sopota',
 'Srbobrana',
 'Sremske Mitrovice',
 'Sremskih Karlovaca',
 'Stare Pazove',
 'Starog grada',
 'Subotice',
 'Surdulice',
 'Surčina',
 'Svilajnca',
 'Svrljiga',
 'Temerina',
 'Titela',
 'Topole',
 'Trgovišta',
 'Trstenika',
 'Tutina',
 'Užica',
 'Valjeva',
 'Varvarina',
 'Velike Plane',
 'Velikog Gradišta',
 'Vladimiraca',
 'Vladičinog Hana',
 'Vlasotinaca',
 'Vranja',
 'Vrbasa',
 'Vrnjačke Banje',
 'Vršca',
 'Zaječara',
 'Zemuna',
 'Zrenjanina',
 'Ćićevca',
 'Ćuprije',
 'Čajetine',
 'Čačka',
 'Čoke',
 'Šapca',
 'Šida',
 'Žablja',
 'Žabara',
 'Žagubice',
 'Žitišta',
 'Žitorađe',
 'Kostolca',
 'Beograda',
 'Prištine',
 'Kosovske Mitrovice']
